### PR TITLE
Refresh the info, add README

### LINKED ISSUE #5: Include Logo on website
Could the logo be included both on the website header and maybe even as a favicon? I think that would make the website more memorable.

### LINKED ISSUE #6: Update the description for v3
De-emphasis multiplatform etc, align with the main repo README
For instance gitextensions/gitextensions#6971

### PR DESCRIPTION
**Pull request by gerhardol**
Closes #6 
Closes #5 

For #5, adds favicon - not completely sure that was requested

### CODE REVIEW

**Comment by gerhardol** [comment]
Already contained the change in #8 , the PR was forgotten...

**Review by RussKie — APPROVED** [review]

**Comment by gerhardol** [comment]
@msftbot merge in 7 days

**Comment by RussKie** [comment]
Thank you

**Comment by viviskas** [comment]
> Closes #6
> Closes #5
> 
> For #5, adds favicon - not completely sure that was requested

**Pull request merged**
